brain_two/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("todos/", include("todos.urls")),
]

todos/urls.py
from django.urls import path

from todos.views import TodoListView, TodoDetailView, TodoCreateView

urlpatterns = [
    path("", TodoListView.as_view(), name="todos_list"),
    path("<int:pk>/", TodoDetailView.as_view(), name="show_todolist"),
    path("create/", TodoCreateView.as_view(), name="todo_create"),
]

todos/models.py
from tkinter import CASCADE
from django.db import models
from django.conf import settings

# Create your models here.
class TodoList(models.Model):
    name = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class TodoItem(models.Model):
    task = models.CharField(max_length=100)
    due_date = models.DateTimeField(blank=True)
    is_completed = models.BooleanField(default=False)
    list = models.ForeignKey(
        "TodoList", related_name="items", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.task

todos/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from django.views.generic.detail import DetailView


from todos.models import TodoItem, TodoList


# Create your views here.


class TodoListView(ListView):
    model = TodoList
    template_name = "todos/list.html"


class TodoDetailView(DetailView):
    model = TodoList
    template_name = "todos/detail.html"


class TodoCreateView(CreateView):
    model = TodoList
    template_name = "todos/create.html"
    fields = ["name"]

    def get_success_url(self):
        return reverse_lazy("todo_detail", kwargs={"pk": self.object.pk})

todos/templates/todos/detail.html
<!DOCTYPE html>

<html>
    <head>
        <title>Todo Lists</title>
    </head>
    <body>
        <header>

        </header>
        <main>
            <div>
                <h1>{{ todolist.name }}</h1>
                <h2>Tasks</h2>
            </div>
            <table>
                <thead>
                    <tr>
                        <th>Task</th>
                        <th>Due Date</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        {% for current in todolist.items.all %}
                        <td>{{ current.task }}</td>
                        <td>{{ current.due_date }}</td>
                    </tr>
                </tbody>
                {% endfor %}
            </table>
        </main>
        <footer>

        </footer>
        
    </body>
</html>

todos/templates/todos/list.html
<!DOCTYPE html>
<html>
    <head>
        <title>Todo Lists</title>
    </head>
    <body>
        <header>

        </header>
        <main>
            <div>
                <h1>My Lists</h1>
            </div>
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Number of Items</th>
                    </tr>
                </thead>
                <tbody>
                    {% for current in todolist_list %}
                    <tr>
                        <td><a href="{% url 'show_todolist' current.id %}">{{ current.name }}</a></td>
                        <td> {{current.items.all|length}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </main>
        <footer>

        </footer>
        
    </body>
</html>